---
encoder:
  name: odb
  output: test_output.odb

sources:
  - name: MultiFileSource
    paths:
      - test_data/UCD
      - test_data/TAU
      - test_data/UHASSELT
      - test_data/WUR

preprocessors:
  #- match: (?P<dataset>test_data)/UCD/AirQuality_(?P<index>\d+)
  - match: test_data/UCD/AirQuality_^(?:(?!~\$).)+\.(?:csv?)$
    metadata:
      class: sample
      origin: UCD
    parser:
      name: CSVParser
      header: true
      metadata_columns:
        - title: TIME
          type: datetime
          identifying: true
          date_format: "%Y-%m-%d %H:%M:%S%z"
          name: an
        - title: BATT
          name: battery
          unit: V
      value_columns:
        - title: CCS811_ECO2
          name: environmental_carbon_dioxide
          unit: ppmV
        - title: CCS811_VOCS
          name: volatile_organic_carbons
          unit: gV
        - title: HUM
          name: relative_humidity
          unit: '%'
        - title: LIGHT
          name: light
          unit: W m**-2
        - title: NOISE_A
          name: noise_level
          unit: dB
        - title: PM_1
          name: particulate_matter_le_0_1_ug
          unit: ug_m**-3
        - title: PM_10
          name: particulate_matter_le_10_ug
          unit: ug_m**-3
        - title: PM_25
          name: particulate_matter_le_2_5_ug
          unit: ug_m**-3
        - title: PRESS
          name: pressure
          unit: psi
        - title: TEMP
          name: air_temperature
          unit: C



  #- match: (?P<dataset>test_data)/UCD/Traffic_(?P<index>\d+)
  - match: (?P<dataset>test_data)/UCD/Traffic_^(?:(?!~\$).)+\.(?:csv?)$
    metadata:
      class: sample
      origin: UCD
    parser:
      name: CSVParser
      header: true
      metadata_columns:
        - title: instance_id
        - title: segment_id
        - title: date
          type: datetime
          identifying: true
          date_format: "%Y-%m-%d %H:%M:%S.%fZ"
          name: an
        - title: interval
        - title: uptime
        - title: timezone
      value_columns:
        - title: heavy
        - title: car
        - title: bike
        - title: pedestrian
        - title: heavy_lft
        - title: heavy_rgt
        - title: car_lft
        - title: car_rgt
        - title: bike_lft
        - title: bike_rgt
        - title: pedestrian_lft
        - title: pedestrian_rgt
        - title: direction
        - title: car_speed_hist_0to70plus
        - title: car_speed_hist_0to120plus
        - title: v85
          name: car_speed_percentile_85

  # TAU
  - match: (?P<dataset>test_data)/TAU/Jerusalem^(?:(?!~\$).)+\.(?:csv?)$
    metadata:
      class: sample
      origin: TAU
    parser:
      name: CSVParser
      header: true
      metadata_columns:
        - title: time
          type: datetime
          identifying: true
          date_format: "%Y-%m-%dT%H:%M:%S.%fZ"
          name: an
        - title: lon
          name: longitude
          unit: degN
        - title: lat
          name: latitude
          unit: degE
      value_columns:
        - title: Temp[°C]
          name: air_temperature
          unit: C
        - title: Press[mbar]
          name: barometric_pressure
          unit: mbar
        - title: Hum[%]
          name: relative_humidity
          unit: '%'
        - title: Alt[m]
          name: altitude
          unit: m
        - title: DP[°C]
          name: dewpoint_temperature
          unit: C
        - title: HDX[°C]
          name: HDX
          unit: C
        - title: Grad[°C/100m]
          name: temperature_lapse_rate
          unit: C/100m
        - title: Speed[km/h]
          name: speed
          unit: km/h
        - title: Solar[]
          name: light
          unit: NaN

  # UHASSELT
  - match: (?P<dataset>test_data)/UHASSELT/meteotracker^(?:(?!~\$).)+\.(?:xlsx?)$
    metadata:
      class: sample
      origin: UHASSELT
    parser:
      name: XLSXParser
      header: true
      metadata_columns:
        - title: Time
          type: datetime
          identifying: true
          date_format: "%Y-%m-%dT%H:%M:%S%z"
          name: an
        - title: Lon
          name: longitude
          unit: degN
        - title: Lat
          name: latitude
          unit: degE
      value_columns:
        - title: Alt [m]
          name: altitude
          unit: m
        - title: Temp [Â°C]
          name: air_temperature
          unit: C
        - title: Hum [%]
          name: relative_humidity
          unit: '%'
        - title: Press [mbar]
          name: barometric_pressure
          unit: mbar
        - title: DP [Â°C]
          name: dew_point
          unit: C
        - title: Radiation
          name: radiation
        - title: Inversion [Â°C/100m]
          name: temperature_lapse_rate
          unit: C_per_100m
        - title: HDX [Â°C]
          name: HDX
          unit: C

  - match: (?P<dataset>test_data)/UHASSELT/smartcitizen_^(?:(?!~\$).)+\.(?:csv?)$
    metadata:
      class: sample
      origin: UHASSELT
    parser:
      name: CSVParser
      header: true
      metadata_columns:
        - title: timestamp
          type: datetime
          identifying: true
          date_format: "%Y-%m-%d %H:%M:%S Z"
          name: an
        - title: battery in % (Battery SCK)
          name: battery_charge
          unit: '%'
      value_columns:
        - title: air humidity in % (SHT31 - Humidity)
          name: relative_humidity
          unit: '%'
        - title: air temperature in ºC (SHT31 - Temperature)
          name: air_temperature
          unit: C
        - title: barometric pressure in kPa (MPL3115A2 - Barometric Pressure)
          name: barometric_pressure
          unit: kPA
        - title: eCO2 in ppm (AMS CCS811 - eCO2)
          name: environmental_CO2
          unit: ppm
        - title: TVOC in ppb (AMS CCS811 - TVOC)
          name: total_volatile_organic_compounds
          unit: ppb
        - title: light in lux (BH1730FVC - Light)
          name: light
          unit: lux
        - title: PM 1 in ug/m3 (PMS5003 - PM1.0)
          name: particulate_matter_1_0
        - title: noise in dBA (ICS43432 - Noise)
          name: noise
          unit: dBA
        - title: PM 10 in ug/m3 (PMS5003 - PM10)
          name: particulate_matter_10
          unit: ug/m3
        - title: PM 2.5 in ug/m3 (PMS5003 - PM2.5)
          name: particulate_matter_2_5
          unit: ug/m3

  # WUR
  - match: test_data/WUR/Weatherstation^(?:(?!~\$).)+\.(?:xlsx?)$
    metadata:
      class: sample
      origin: WUR
    parser:
      name: CSVParser
      header: true
      metadata_columns:
        - title: Timestamps
          type: datetime
          identifying: true
          date_format: "%d.%m.%y %H:%M"
          name: an
      value_columns:
        - title: kPa Vapor Pressure
          name: vapor_pressure
          unit: kPa
        - title: degree_C Air Temperature
          name: air_temperature
          unit: C
        - title: kPa VPD
          name: vapor_pressure_deficit
          unit: kPa
        - title: degrees Wind Direction
          name: wind_direction
          unit: degrees
        - title: m/s Wind Speed
          name: wind_speed
          unit: m/s
        - title: m/s Gust Speed
          name: wind_gust_speed
          unit: m,/s

  - match: test_data/WUR/Netatmo_^(?:(?!~\$).)+\.(?:xls?)$
    metadata:
      class: sample
      origin: UCD
    parser:
      name: CSVParser
      header: true
      header_columns:
        - title: Name
          name: location
        - title: Long
          name: longitude
          unit: degE
        - title: Lat
          name: latitude
          unit: degN
        - title: ModuleName
          name: module
      metadata_columns:
        - title: Timestamp
          type: seconds_since_epoch
          name: seconds_since_epoch
          unit: seconds
        - title: Timestamp
          type: seconds_since_epoch
          identifying: true
          date_format: "%Y/%m/%d %H:%M:%S"
          tz: "Europe/Amsterdam"
          name: an
      value_columns:
        - title: CCS811_ECO2
          name: environmental_carbon_dioxide
          unit: ppmV
