actions:
  - class: SmartCitizenKitSource
    copy_metadata_to_columns:
      - station_name
      - station_id
      - lat
      - lon
      - created_at
      - city
      - country
      - author
    
    cache_directory: inputs/smart_citizen_kit
    mappings: !include mappings.yaml # Used to rename things before going into the metadata db

  - class: CSVParser
    mappings: !include mappings.yaml
    
    identifying_keys:
      - time
      
    metadata_keys:
      - station_name
      - station_id
      - author
      - lat
      - lon
      - created_at
      - city
      - country

  - class: Splitter
    identifying_keys:
      - time
      
    metadata_keys:
      - station_name
      - author
      - lat
      - lon
      - created_at
      - city
      - country


  - class: NewTimeAggregator
    granularity_hours: 1
    min_emit_after_hours: 96
    time_direction: forwards

  - class: ODCEncoder
    output: outputs/{source}/odb/{observation_variable}/{observation_variable}_{time_slice.start_time}.odb
    MARS_keys: !include MARS_keys.yaml