global_config:
  canonical_variables: !include canonical_variables.yaml
  config_path: .
  data_path: ../data/

pipeline:
  - sources
  - other_processors
  - parsers
  - aggregators
  - encoders
  

sources:
  - class: MultiFileSource
    metadata:
        state: big_file
        source: sensor.community
    paths:
      - "**/*.csv"
    basepath: inputs/sensor_community

# This is needed because the sensor.community monthly files are so big
# They need to be processes in chunks to avoid running out of memory
other_processors:
  - class: CSVChunker
    match:
      - state: big_file
        source: acronet
    metadata:
       state: raw
       
  - class: QualityControl
    test_variable: a_string
    match:
      - state: time_aggregated
        source: sensor.community
    

encoders:
  - class: CSVEncoder
    match:
    - source: acronet
      state: "quality_controlled"
    output: data/outputs/{source}/csv/{observation_variable}/{observation_variable}_{time_span.start_time}.csv
    metadata:
      state: encoded

  - class: ODCEncoder
    match:
      - source: acronet
        state: "quality_controlled"
    output: data/outputs/{source}/odb/{observation_variable}/{observation_variable}_{time_span.start_time}.odb
    MARS_keys: !include MARS_keys.yaml
    


aggregators:
  - class: TimeAggregator
    match:
    - source: acronet
      state: parsed
    granularity: 1min # min, H, D, M see https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-period-aliases
    emit_after_hours: 48

parsers:
  - class: CSVParser
    match:
      - state: raw
        source: acronet
    separator: ";"
    custom_nans:
      - unknown
      - unavailable


    identifying_columns:
      - name: time
        key: timestamp
        type: datetime


    metadata_columns:
      - name: station_id
        key: sensor_id
      - name: sensor_type
      - name: location
      - name: lat
        unit: "°"
      - name: lon
        unit: "°"
      # - name: air_pressure_near_surface
      #   key: pressure
      #   unit: Pa
      # - name: altitude
      #   unit: m


    value_columns:
      - name: air_temperature_near_surface
        key: temperature
        unit: "°C"
      - name: relative_humidity_near_surface
        key: humidity
        unit: "%"
      - name: pressure_sealevel
        key: pressure
        unit: "hPa"
