[project]
name = "meteotracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ionbeam-client",
    "pydantic-settings>=2.14",
    "pyyaml>=6.0.3",
    "httpx>=0.28.1",
    "httpx-retries>=0.2.0",
    "click>=8.1.0",
]

[tool.uv.sources]
ionbeam-client = { workspace = true }

[project.scripts]
meteotracker = "meteotracker:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
