globals:
  # A list of observables with name, unit and other metadata that the incoming datastreams get mapped to.
  canonical_variables: !include canonical_variables.yaml

  data_path: ../data/
  cache_path: ../data/cache/
  fdb_root: ../data/fdb_root

  # The secrets file to use
  # Todo: add a mechanism to template values from this file into the config with a constructor like !secrets meteotracker.password
  secrets_file: config/secrets.yaml
  
  # Files to configure the FDB
  fdb_schema_path: config/schema
  metkit_language_template: config/language.yaml.template
  custom_mars_keys: ["platform", "observation_variable", "external_id","internal_id", "aggregation_type", "version"]
  echo_sql_commands: false

  # Whether sources should attempt to access external services or just use locally cached data
  # Can be overridden at the command line
  download: true
  ingest_to_pipeline: true
  overwrite_fdb: true


 # Global constants that override things in the sources and timeaggregator
  ingestion_time_constants:
    query_timespan: 
      start: datetime.now(tz=timezone.utc) - timedelta(days = 60)
      end: datetime.now(tz=timezone.utc) - timedelta(minutes = 10)

    # How big a data granule should be
    granularity:
      hours: 1

    # In what direction the time aggregator expects data to arrive. 
    time_direction: forwards

sources:
  # - sensor.community
  - acronet
  - meteotracker
  - smart_citizen_kit

environments:
  local:
    api_hostname: ""
    overwrite_fdb: true
    postgres_database:
      host: localhost
      port: 9875

  ewc:
    fdb_root: /media/data/fdb
    data_path: /media/data/data
    cache_path: /media/data/cache
    api_hostname: ""
    overwrite_fdb: true
    postgres_database:
      host: localhost
      port: 9875

  dev:   
    api_hostname: http://iotdev-001:18201/api/v1/ # (requires an SSH tunnel)
    # api_hostname: https://ionbeam-dev.ecmwf.int/api/v1/ # Deployed Frontend (need to fix)
    postgres_database:
      host: iotdev-001
      port: 9875

  test: 
    api_hostname: https://ionbeam-test.ecmwf.int/api/v1
    postgres_database:
      host: iotdev-002
      port: 9875