globals:
  # A list of observables with name, unit and other metadata that the incoming datastreams get mapped to.
  canonical_variables: !include canonical_variables.yaml

  # Where to look for input data
  data_path: ../data/
  cache_path: ../data/cache/

  # The secrets file to use
  # Todo: add a mechanism to template values from this file into the config with a constructor like !secrets meteotracker.password
  secrets_file: config/secrets.yaml
  
  # Files to configure the FDB
  fdb_schema_path: config/schema
  metkit_language_template: config/language.yaml.template
  custom_mars_keys: ["platform", "observation_variable", "external_id","internal_id", "aggregation_type"]


  # Whether sources should attempt to access external services or just use locally cached data
  # Can be overridden at the command line
  offline: false
  overwrite: false

 # Global constants that override things in the sources and timeaggregator
  ingestion_time_constants:
    query_timespan: 
      - datetime.now(tz=timezone.utc) - timedelta(hours = 5)
      - datetime.now(tz=timezone.utc)
    
    # How old a data granule must be before the aggregator considers it to be "complete"
    # This allows time for late data to arrive
    emit_after_hours: 20

    # How big a data granule should be
    granularity:
      minutes: 5

    # In what direction the time aggregator expects data to arrive. 
    time_direction: forwards

sources:
  # - sensor.community
  - acronet
  - meteotracker
  #- smart_citizen_kit

environments:
  local:
    fdb_root: /Users/math/git/IonBeam_bundle/data/fdb_root
    api_hostname: ""
    offline: true
    overwrite: true
    postgres_database:
      host: localhost
      port: 9875

  ewc:
    fdb_root: /media/data/fdb_root
    api_hostname: ""
    offline: true
    overwrite: true
    postgres_database:
      host: localhost
      port: 9875

  dev:   
    api_hostname: http://iotdev-001:18201/api/v1/ # (requires an SSH tunnel)
    # api_hostname: https://ionbeam-dev.ecmwf.int/api/v1/ # Deployed Frontend (need to fix)
    offline: false
    overwrite: false
    postgres_database:
      host: iotdev-001
      port: 9875

  test: 
    api_hostname: https://ionbeam-test.ecmwf.int/api/v1
    offline: false
    overwrite: false
    postgres_database:
      host: iotdev-002
      port: 9875