---
# This is an example for the expected format of secrets.yaml
# Do not put anything secret in here because if you accidentally commit it to Github
# those credentials will be compromised. Copy this to secrets.yaml and edit it, 
# secrets.yaml is in the .gitignore so is more difficult to accidentally commit.

headers: # This allows server operators to contact you if you're sending too many requests
    'User-Agent': 'ECMWF IOT Scraper'
    'From': 'you.email@example.com'

CIMA_API:  
  client_id :
  client_secret :
  username :
  password :


MeteoTracker_API:
  email :
  password : 

polytope:
    user_email: 
    user_key: 

breathe_london:
  api_key:

