---
global_config:
  canonical_variables: !include canonical_variables.yaml
  config_path: .
  data_path: ../data

pipeline:
  - sources

sources:
  - class: MeteoTrackerSource
    cache_directory: data/inputs/meteotracker
    secrets_file: secrets.yaml
    end_date: "2023-07-26"
    start_date: "2020-01-01"
    static_metadata_columns:
      - name: track_id
        key: id
      - name: author
      - name: offset_tz


  # - name: CIMASource
  #   source: "Acronet"
  #   cache_directory: data/inputs/cima
  #   secrets_file: secrets.yaml
  #   end_date: "2023-07-26"
  #   start_date: "2020-01-01"
  #   frequency: 3D # 3 days is the max API request
  #   static_metadata_columns:
  #     - name: station_id
  #       key: id
  #     - name: lat
  #     - name: lon

  # - name: SensorCommunitySource
  #   source: "Sensor.Community"
  #   cache_file: data/inputs/cache/sensor_community_html_cache.pickle
  #   cache_directory: data/inputs/sensor_community
  #   start_date: "2023-07-26"
  #   end_date: "2020-01-01"
