global_config:
  canonical_variables: !include canonical_variables.yaml
  config_path: .
  data_path: ../data/

pipeline:
  - sources
  - other_processors
  - parsers
  - aggregators
  - encoders
  

sources:
  - class: MultiFileSource
    metadata:
        state: big_file
        source: sensor.community
    paths:
      - "**/*.csv"
    basepath: inputs/sensor_community

# This is needed because the sensor.community monthly files are so big
# They need to be processes in chunks to avoid running out of memory
other_processors:
  - class: CSVChunker
    match:
      - state: big_file
        source: sensor.community
    metadata:
       state: raw

encoders:
  - class: CSVEncoder
    match:
    - source: sensor.community
      state: "time_aggregated"
    output: data/outputs/{source}/csv/{observation_variable}/{observation_variable}_{time_slice.start_time}.csv
    metadata:
      state: encoded

  - class: ODCEncoder
    match:
      - source: sensor.community
        state: "time_aggregated"
    output: data/outputs/{source}/odb/{observation_variable}/{observation_variable}_{time_slice.start_time}.odb
    MARS_keys: !include MARS_keys.yaml
    




aggregators:
  - class: TimeAggregator
    match:
    - source: sensor_community
      state: parsed
    granularity: 1min # min, H, D, M see https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-period-aliases
    emit_after_hours: 48

parsers:
  - class: CSVParser
    match:
      - state: raw
        source: sensor.community
    separator: ";"
    custom_nans:
      - unknown
      - unavailable


    identifying_columns:
      - name: time
        key: timestamp
        type: datetime

    # the following identifies the data in the monthly CSV's
    metadata_columns:
      - name: sensor_id
        key: sensor_id
      - name: sensor_type
        key: sensor_module
      - name: location
        key: station_id

      - name: lat
        unit: "°"
      - name: lon
        unit: "°"
      # - name: pressure
      #   key: pressure
      #   unit: Pa
      # - name: altitude
      #   unit: m

    sensor_module:
    # do NOT use sensor module dht22! And sensor module ppd42ns has weird units that we need to check first 
      - name: sds11
        observations: [P1, P2]
        range: [0, 999]
        precision: 10  # plusminus in "um m^-3"

      - name: pms30003
        observations: [P0, P1, P2]
        range: [0, 1000]
        precision: 10 # plusminus in "um m^-3"

      - name: pms50003
        observations: [P0, P1, P2]
        range: [0, 1000]
        precision: 10 # plusminus in "um m^-3"

      - name: pms30003
        observations: [P0, P1, P2]
        range: [0, 1000]
        precision: 10 # plusminus in "um m^-3"

      - name: hpm
        observations: [P1, P2]
        range: [0, 1000]
        precision: 15 # plusminus in "um m^-3"

      - name: bme280
        observations: [humidity, pressure, temperature]
        range: [[0, 100], [-40, 85], [300, 1100]] # in ["%", "degC", "Pa"]
        precision: [3, 1, 1] # plusminus

      - name: bmp280
        observations: [pressure, temperature]
        range: [[-40, 85], [300, 1100]] # in ["degC", "Pa"]
        precision: [1, 1] # plusminus

      - name: bmp180
        observations: [pressure, temperature]
        range: [[-40, 85], [300, 1100]] # in ["degC", "Pa"]
        precision: [1, 1] # plusminus

      - name: ds18b20
        observations: [temperature]
        range: [-55, 125] # in "degC"
        precision: 0.5 # plusminus

      - name: htu21d
        observations: [temperature, humidity]
        range: [[-40, 125], [0, 100]] # in ["degC", "%"]
        precision: [0.3, 2] # plusminus




    value_columns:
      - name: temperature
        key: air_temperature
        unit: "°C"
      - name: humidity
        key: relative_humidity
        unit: "%"
      - name: pressure
        key: pressure
        unit: "Pa"    # I see some random values in hPa, and this is also what is stated in the documentation by sensor.community
      - name: altitude
        key: altitude
        unit: "m"

      - name: P0
        key: particulate_matter_1um
        unit: "um m^-3"
      - name: P1
        key: particulate_matter_10um
        unit: "um m^-3"
      - name: P2
        key: particulate_matter_2.5um
        unit: "um m^-3"

