actions:
  - class: MultiFileSource
    metadata:
        state: raw
        source: sensor.community
    paths:
      - "**/*.csv"
      - "**/*.zip"
    basepath: inputs/sensor_community_archive

  - class: CSVChunker
    match:
      - source: sensor.community
        state: "raw"
    metadata:
      state: chunked
      source: sensor.community
    rows_per_chunk: 10_000
    separator: ";"

  - class: ODCEncoder
    metadata:
      state: odc_encoded
      source: sensor.community
    match:
      - source: sensor.community
        state: time_aggregated
    output: data/outputs/{source}/odb/{observation_variable}/{observation_variable}_{time_slice.start_time}.odb
    MARS_keys: !include MARS_keys.yaml
    fdb_schema: |
      expver:     Expver;
      date:       Date;
      time:       Time;

      [ project, platform
            [ observation_variable
                    [ date, time ]]]

  - class: TimeAggregator
    metadata:
      state: time_aggregated
      source: sensor.community
    match:
    - source: sensor.community
      state: filtered
    granularity: 1H # min, H, D, M see https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-period-aliases
    emit_after_hours: 48

  - class: DateFilter
    from_date: 2017-10-28
    to_date: 2017-10-29
    column: time

    metadata:
      state: filtered
      source: sensor.community
    match:
    - source: sensor.community
      state: parsed


  - class: CSVParser
    metadata:
      state: parsed
      source: sensor.community
    match:
      - state: chunked
        source: sensor.community
    custom_nans:
      - unknown
      - unavailable


    identifying_columns:
      - name: time
        key: timestamp
        type: datetime


    metadata_columns:
      - name: station_id
        key: sensor_id
      - name: sensor_type
      - name: location
      - name: lat
        unit: "°"
      - name: lon
        unit: "°"
      # - name: air_pressure_near_surface
      #   key: pressure
      #   unit: Pa
      # - name: altitude
      #   unit: m


    value_columns:
      - name: air_temperature_near_surface
        key: temperature
        unit: "°C"

      - name: relative_humidity_near_surface
        key: humidity
        unit: "%"

      - name: air_pressure_near_surface
        key: pressure
        unit: Pa

      - name: particulate_matter_1
        key: P0
        unit: "μg/m3"

      - name: particulate_matter_10
        key: P1
        unit: "μg/m3"

      - name: particulate_matter_2_5
        key: P2
        unit: "μg/m3"

      - name: durP1
        discard: True
      - name: ratioP1
        discard: True
      - name: durP2
        discard: True
      - name: ratioP2
        discard: True
