actions:
  - class: AcronetSource
    mappings: !include mappings.yaml
    copy_metadata_to_columns:
      external_station_id: id
      station_name: name
      lat: lat
      lon: lon

  - class: SetConstants
    set:
      platform: acronet
      aggregation_type: chunked

  - class: ComputeStationId
  - class: ComputeChunkDateTime

  - class: CanonicaliseColumns
    mappings: !include mappings.yaml
    move_to_front:
      - station_id
      - external_station_id
      - station_name
      - author
      - aggregation_type
      - chunk_date
      - platform
      - chunk_time
      - datetime
      - lat
      - lon

  - class: UpdateStationMetadata      

  - class: SplitOnColumnValue
    column: station_id

  - class: DropNaNColumns
  - class: DropNaNRows
  - class: DropEmpty

  - class: ComputeMARSIdentifier
    lookup:
      class: const.rd
      expver: const.xxxx
      stream: const.lwda
      aggregation_type: data.aggregation_type
      platform: data.platform
      date: data.chunk_date
      internal_id: data.station_id
      time: data.chunk_time
      version: const.1

    forward_to_names: ["final_processing"]

      





