actions:
  - class: AcronetSource
    mappings: !include mappings.yaml

  - class: DropEmpty

  - class: ExtractMetaData
    copy_metadata_to_columns:
      station_id: station.id
      station_name: station.name
      lat: station.lat
      lon: station.lon
      author : author

  - class: CanonicaliseColumns
    mappings: !include mappings.yaml

  - class: AddAcronetMetadata

  - class: ComputeDateTime

  - class: ComputeMARSIdentifier
    lookup:
      class: const.rd
      expver: const.xxxx
      stream: const.lwda
      aggregation_type: const.chunked
      platform: const.acronet
      date: metadata.date
      internal_id: metadata.internal_id
      time: metadata.time

  - class: SimpleODCEncoder

