actions:
  - class: AcronetSource
    mappings: !include mappings.yaml
    copy_metadata_to_columns:
      - station_id
      - station_name
      - lat
      - lon
      - start_time

  - class: CSVParser
    mappings: !include mappings.yaml
    identifying_keys:
      - time

    metadata_keys:
      - author
      - station_id
      - lat
      - lon

  - class: AddAcronetMetadata

  - class: ODCEncoder
    split_data_columns: False
    output: outputs/{source}/odb/{external_id}_{start_time}.odb
    MARS_keys: !include MARS_keys_per_track.yaml

  - class: FDBWriter
    config:
      engine: toc
      spaces:
      - handler: Default
        roots:
        - path: /Users/math/git/IonBeam_bundle/data/fdb_root