- name: class
  fill_method: constant
  value: rd
  dtype: STRING

- name: expver
  dtype: STRING
  fill_method: constant
  value: xxxx
  column_description: mars key - experiment id

- name: stream
  dtype: STRING
  fill_method: constant
  value: lwda
  column_description: mars key - forecasting system used to generate data

- name: project
  dtype: STRING
  fill_method: constant
  value: I-CHANGE
  column_description: Which project this data is part of. Currently I-Change, AD4GD or Any

- name: platform
  dtype: STRING
  fill_method: constant
  value: Acronet
  column_description: 'The aggregation platform that we retrieved this data from.'

- name: aggregation_type
  dtype: STRING
  fill_method: constant
  value: chunked
  column_description: 'The aggregation platform that we retrieved this data from.'

- name: source_name
  fill_method: from_data
  key: author
  column_description: 'The name of the individual entity data came from.'
  dtype: STRING

- name: external_id
  dtype: STRING
  fill_method: function
  key: station_id
  column_description: 'A unique id for the individual entity data came from.'

- name: internal_id
  dtype: STRING
  fill_method: function
  key: station_id_hash
  column_description: 'A unique id for the individual entity data came from.'

- name: date
  dtype: INTEGER
  column_description: obs. date
  fill_method: function
  key: decimal_encoded_date

- name: datetime
  dtype: STRING
  column_description: The datetime as ISO 8601
  fill_method: function
  key: datetime

- name: altitude
  dtype: DOUBLE
  column_description: altitude
  fill_method: function
  key: altitude

# lat and lon coords
- name: lat
  column_description: latitude
  dtype: DOUBLE
  fill_method: from_data
  key: lat

- name: lon
  column_description: longitude
  dtype: DOUBLE
  fill_method: from_data
  key: lon
