# This file will contain a list of our canonical variables various metadata associated with them

# This is our canonical name for each variable
# Where possible I have used the same keys as defined by the WMO, see WMO_variables.yaml
# When that's not possible we need to define the key, unit and definition
# Possibly other variables too

# for dtype use object aliases from https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes
# default dtype is float64

- name: time
  dtype: datetime64[ns, UTC]
  desc: The time that the observation was made.

- name: offset_tz
  desc: Uncertain what this means in the Metrotracker data.
  dtype: object

- name: lat
  unit: "°"
  CRS: WGS84
  desc: "The lattitude of the observation, referenced to WGS84 (EPSG: 4326)"

- name: lon
  unit: "°"
  CRS: WGS84
  desc: "The longitude of the observation, referenced to WGS84 (EPSG: 4326)"

- name: altitude
  unit: m
  desc: "The altitude of the observation, referenced to WGS84 (EPSG: 4326)"

- name: author
  dtype: object
  desc: The author field from the Meteotracker data

- name: track_id
  desc: A unique identifer for a single recorded track from a mobile sensor.
  dtype: object

- name: station_id
  desc: A unique identifer for a stationary sensor.
  dtype: object

- name: sensor_type
  dtype: object

- name: location
  dtype: int

- name: observation_id
  desc: A unique identifer for a stationary sensor.
  dtype: object

- name: air_temperature_near_surface
  output: true
  unit: K
  codetype: 35 # Land TEMP
  varno: 39 # 2m temperature (K)
  obstype: 5 # TEMP

- name: relative_humidity_near_surface
  output: true
  unit: "%"
  WMO: true # indicates this exact name is defined by the WMO
  codetype: 14 # Automatic Land SYNOP
  varno: 58 # 2m rel. humidity
  obstype: 1 # SYNOP


- name: internal_temperature
  unit: K
  desc: The internal temperature of the sensor.

- name: air_pressure_near_surface
  unit: Pa
  WMO: False #the WMO use hPa as the unit

- name: pressure_sealevel
  unit: Pa



- name: co2
  unit: ppm
  WMO: true

- name: wind_gust
  unit: m.s-1 
  WMO: true

- name: wind_gust_direction
  unit: "°"

- name: dew_point_temperature
  unit: K
  WMO: true

- name: wind_direction_near_surface
  unit: "°"
  WMO: true

- name: wind_speed_near_surface
  unit: "m/s"
  WMO: true

- name: rain_gauge
  unit: "mm"

- name: wind_direction
  unit: "Degrees"

- name: anemometer
  unit: "m/s"


- name: radiometer
  unit: "W/m^2"
- name: battery_level
  unit: "V"


- name: thermometer_min
  unit: K
- name: thermometer_max
  unit: K

- name: signal_strength
  unit: "CSQ"

- name: altitude
  unit: m

- name: P1
  output: true
  codetype: -1 #
  varno: -1 #
  obstype: -1 #

- name: durP1

- name: ratioP1

- name: P2
  output: true

- name: durP2

- name: ratioP2

