from typing import Protocol


class IngestionMetricsProtocol(Protocol):
    def observe_data_points(self, dataset: str, count: int) -> None: ...

    def observe_duration(self, dataset: str, seconds: float) -> None: ...

    def record_batch_processed(self, dataset: str) -> None: ...

    def record_error(self, dataset: str, error_type: str) -> None:
        """Record an ingestion error."""
        ...


class CoordinatorMetricsProtocol(Protocol):
    def window_skipped(self, dataset: str, reason: str) -> None: ...

    def window_enqueued(self, dataset: str) -> None: ...

    def set_queue_size(self, dataset: str, size: int) -> None: ...

    def observe_duration(self, dataset: str, seconds: float) -> None: ...


class BuilderMetricsProtocol(Protocol):
    def build_started(self, dataset: str) -> None: ...

    def build_succeeded(self, dataset: str) -> None: ...

    def build_failed(self, dataset: str) -> None: ...

    def requeued(self, dataset: str, reason: str) -> None: ...

    def observe_build_duration(self, dataset: str, seconds: float) -> None: ...

    def observe_rows_exported(self, dataset: str, rows: int) -> None: ...

    def record_dataset_published(self, dataset: str, status: str) -> None: ...


class SchedulerMetricsProtocol(Protocol):
    def record_trigger(self, source: str, status: str) -> None: ...

    def observe_trigger_delay(self, source: str, seconds: float) -> None: ...

    def set_next_run_timestamp(self, source: str, timestamp: float) -> None: ...

    def set_enabled_status(self, source: str, enabled: bool) -> None: ...


class HealthMetricsProtocol(Protocol):
    def set_component_status(self, component: str, healthy: bool) -> None: ...

    def observe_health_check_duration(self, component: str, seconds: float) -> None: ...
