actions:
  - class: MeteoTrackerSource
    mappings: !include mappings.yaml
    cache_directory: cache/meteotracker

    # wkt_bounding_polygon: "POLYGON ((7.008125020793557 45.56326584931264, 7.008125020793557 38.29891947585193, 10.582293217633804 38.29891947585193, 10.582293217633804 45.56326584931264, 7.008125020793557 45.56326584931264))"
    author_patterns:
      Bologna:
          bologna_living_lab_{}: range(1,21)
      Barcelona:
          barcelona_living_lab_{}: range(1, 16)
          Barcelona_living_lab_{}: range(1, 16)
      Genoa:
          CIMA I-Change: range(1,2)
          genova_living_lab_{}: range(1,30)
      Amsterdam:
          Amsterdam_living_lab_ICHANGE: range(1,2)
          Gert-Jan Steeneveld: range(1,2)
      # #Hasselt:
      # #    Don't ingest me! hasselt_living_lab_{}: range(1,16)
      Ouagadougou:
          llwa_living_lab_{}: range(1,16)
      Dublin:
          "Dublin LL": range(1,2)
      Jerusalem:
          jerusalem_living_lab_{}: range(1,16)

  - class: ExtractMetaData
    copy_metadata_to_columns:
      author: author
      living_lab: living_lab
    copy_to_metadata:
       external_id: id

  - class: CanonicaliseColumns
    mappings: !include mappings.yaml
    move_to_front:
      -  datetime
      -  external_id
      -  author
      -  lat
      -  lon

  - class: ComputeChunkDateTime
  - class: ComputeStationId

  - class: ComputeMARSIdentifier
    lookup:
      class: const.rd
      expver: const.xxxx
      stream: const.lwda
      aggregation_type: data.aggregation_type
      platform: const.meteotracker
      date: metadata.date
      internal_id: metadata.internal_id
      time: metadata.time
      version: const.1

  - class: AddMeteotrackerMetadata
    forward_to_names: ["final_processing"]

