# See https://app.meteotracker.com/html/api-docs/#numericPoint for mapping
- name: time
  key: time
  type: datetime

- name: author
  key: session.author

- name: offset_tz
  key: session.offset_tz

- name: track_id
  key: session.id

- name: lat
  unit: EPSG:4326

- name: lon
  unit: EPSG:4326

- name: altitude
  key: a
  unit: EPSG:4326

- name: air_pressure_near_surface
  key: P
  unit: mbar

- name: air_temperature_near_surface
  key: T0
  unit: "°C"
- name: relative_humidity_near_surface
  key: H
  unit: "%"
# This would cause issues because we're also outputing it as a metadata_column too
# - name: air_pressure_near_surface
#   key: P
#   unit: mbar
- name: potential_temperature
  key: tp
  unit: K

- name: dew_point_temperature
  key: td
  unit: "°C"
- name: humidity_index
  key: HDX
  unit: "°C"
- name: vertical_temperature_gradient
  key: i
  unit: "°C/100m"
  # ignore: true
- name: wind_speed_near_surface
  key: s
  unit: km/h
- name: solar_radiation_index
  unit: 1
  key: L
- name: bluetooth_RSSI
  key: bt
  unit: dBm
- name: carbon_dioxide
  key: CO2
  unit: ppm
- name: particulate_matter_1
  key: m1
  unit: "μg/m3"
- name: particulate_matter_1
  key: m1
  unit: "μg/m3"
- name: particulate_matter_2_5
  key: m2
  unit: "μg/m3"
- name: particulate_matter_4
  key: m4
  unit: "μg/m3"
- name: particulate_matter_10
  key: m10
  unit: "μg/m3"
- name: particulate_matter_particle_number_0_5
  key: n0
  unit: "#/cm3"
- name: particulate_matter_particle_number_1
  key: n1
  unit: "#/cm3"
- name: particulate_matter_particle_number_2_5
  key: n2
  unit: "#/cm3"
- name: particulate_matter_particle_number_4
  key: n4
  unit: "#/cm3"
- name: particulate_matter_particle_number_10
  key: n10
  unit: "#/cm3"
- name: typical_particle_size
  key: tps
  unit: "μm"
- name: EPA_Air_Quality
  unit: 1
  key: EAQ
- name: Fast_Air_Quality
  unit: 1
  key: FAQ
- name: ozone
  key: O3
  unit: "ppb"
- name: observation_id
  key: _id